/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Createvital;
import model.VitalSignHistory;

/**
 *
 * @author admin
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory history) {
        initComponents();
        this.history= history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcreatevital = new javax.swing.JLabel();
        lbltemp = new javax.swing.JLabel();
        lblpressure = new javax.swing.JLabel();
        lblpulse = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txttemp = new javax.swing.JTextField();
        txtpressure = new javax.swing.JTextField();
        txtpulse = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        lblcreatevital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcreatevital.setText("CREATE VITAL SIGNS");

        lbltemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltemp.setText("Temprature :");

        lblpressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpressure.setText("Blood Pressure :");

        lblpulse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpulse.setText("Pulse :");

        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date :");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcreatevital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(lblpulse)
                    .addComponent(lblpressure)
                    .addComponent(lbltemp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttemp)
                    .addComponent(txtpressure)
                    .addComponent(txtpulse)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDate, lblpressure, lblpulse, lbltemp, txtdate, txtpressure, txtpulse, txttemp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblcreatevital, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltemp)
                    .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpressure)
                    .addComponent(txtpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpulse)
                    .addComponent(txtpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnsave)
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        double temp = Double.parseDouble(txttemp.getText());
        double pressure = Double.parseDouble(txtpressure.getText());
        int pulse = Integer.parseInt(txtpulse.getText());
        String date = txtdate.getText();
        
        Createvital vs = history.addNewVital();
        
        vs.setTemp(temp);
        vs.setBloodpressure(pressure);
        vs.setPulse(pulse);
        vs.setDate(date);
                
        JOptionPane.showMessageDialog(this, "New Vital Sign Added.");
        
        txttemp.setText("");
        txtpressure.setText("");
        txtpulse.setText("");
        txtdate.setText("");
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblcreatevital;
    private javax.swing.JLabel lblpressure;
    private javax.swing.JLabel lblpulse;
    private javax.swing.JLabel lbltemp;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtpressure;
    private javax.swing.JTextField txtpulse;
    private javax.swing.JTextField txttemp;
    // End of variables declaration//GEN-END:variables
}
